### ISSUE TITLE
Should print log messages to STDOUT as documented instead of STDERR

### ISSUE THREAD

**Issue by xtaran** [dmachard/pdns-protobuf-receiver#2]
Hi,

it took me quite a while to realise why I get log messages on the command line, but not when I call `pdns_logger` from inside `syslog-ng`: `pdns_logger` is not sending its log messages to STDOUT as documented in several places in `README.md` but to STDERR instead.

Please change that to STDOUT so that it works as documented and as (obviously) expected.

My current workaround is to append `2>&1` to the commandline called by `syslog-ng`.

**Comment by dmachard** [comment]
fixed in release 0.0.3

**Comment by xtaran** [comment]
Yay, thanks for fixing both, #2 and #3 so quick! Will have a look at the new release(s) soon.

Both issues are still marked as open though. Seems as if the `fix issue #…` wasn't enough (despite I would have expected that it is).

I'm btw. working on a package for Debian. See https://bugs.debian.org/972607 and https://salsa.debian.org/debian/pdns-logger
